### ISSUE TITLE
Typo in line 14

### ISSUE THREAD

**Issue by cmuyehara** [Danko-Lab/proseq2.0#2]
There's a typo in line 14 of proseq2.0.bash. "ehco" should be "echo".

**Comment by dankoc** [comment]
Thank you for reporting this! Fixed!

**Comment by shaopei** [comment]
Thank you for fixing that. I planned to, but I forgot.

Shao-Pei Chou
PhD Candidate
Graduate Field of Genetics, Genomics and Development
Cornell University
Ithaca, NY 14853, USA
